services:
    twitter_header_clock:
        build: .
        image: twitter_header_clock
        container_name: twitter_header_clock
        command: ["sh", "-c", "./twitter_header_clock.py | tee -a log.txt"]
        volumes:
            - .:/app
        restart: always

